
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("story/new", "Create story")) ?>
</div>

<?php echo $this->tag->form(array("story/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search story</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="text">Text</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("text", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date">Date</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("date", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="author">Author</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("author", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
