<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("story/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("story/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Text</th>
            <th>Date</th>
            <th>Author</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $story) { ?>
        <tr>
            <td><?php echo $story->getId() ?></td>
            <td><?php echo $story->getTitle() ?></td>
            <td><?php echo $story->getText() ?></td>
            <td><?php echo $story->getDate() ?></td>
            <td><?php echo $story->getAuthor() ?></td>
            <td><?php echo $this->tag->linkTo(array("story/edit/" . $story->getId(), "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("story/delete/" . $story->getId(), "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("story/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("story/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("story/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("story/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
